-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:

-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- Find the sum of all the even-valued terms in the sequence which do not
-- exceed four million.

fib :: Int -> Int -> [Int]
fib 0 _ = []
fib m n = m : (fib n (m+n))

main = do
  let even_fibs = (takeWhile (<4000000)) $ (filter even) (fib 1 2)
  print $ sum even_fibs